# Site settings
author: Amana Ammishaddai
title: MishinToMars
header-img: img/home-bg.png
email: amana.ammi@gmail.com
copyright_name: Amana Ammishaddai
description: > # this means to ignore newlines until "baseurl:"
  From Day One To Infinity!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Amonsta

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
